//! Test code generation from recorded sessions.
//!
//! Converts a [`RecordedSession`] into a self-contained Rust test file that
//! replays DOM interactions through the `VictauriClient` API and optionally
//! asserts on IPC outcomes and state transitions.

use chrono::Utc;

use crate::event::{AppEvent, InteractionKind, IpcResult};
use crate::recording::RecordedSession;

/// Options for controlling test code generation.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct CodegenOptions {
    /// Name of the generated test function.
    pub test_name: String,
    /// Whether to include IPC assertions after interactions.
    pub include_ipc_assertions: bool,
    /// Whether to include state verification assertions.
    pub include_state_checks: bool,
    /// Whether to add timing comments showing relative timestamps.
    pub include_timing_comments: bool,
}

impl Default for CodegenOptions {
    fn default() -> Self {
        Self {
            test_name: "recorded_flow".to_string(),
            include_ipc_assertions: true,
            include_state_checks: true,
            include_timing_comments: true,
        }
    }
}

/// Generates a Rust test file from a recorded session using default options.
///
/// This is a convenience wrapper around [`generate_test`] with
/// [`CodegenOptions::default()`].
#[must_use]
pub fn generate_test_default(session: &RecordedSession) -> String {
    generate_test(session, &CodegenOptions::default())
}

/// Generates a Rust test file from a recorded session.
///
/// Converts DOM interactions into `VictauriClient` API calls and IPC events
/// into verification assertions. The generated test is self-contained and
/// can be run with `cargo test`.
#[must_use]
pub fn generate_test(session: &RecordedSession, options: &CodegenOptions) -> String {
    let mut out = String::with_capacity(2048);

    // File header
    let date = Utc::now().format("%Y-%m-%d");
    out.push_str(&format!("// Generated by victauri record -- {date}\n"));
    out.push_str(&format!("// Session: {}\n", session.id));
    out.push_str("\nuse victauri_test::VictauriClient;\n\n");

    // Test function
    out.push_str("#[tokio::test]\n");
    out.push_str(&format!("async fn {}() {{\n", options.test_name));
    out.push_str("    let mut client = VictauriClient::discover().await.expect(\"connect to Tauri app\");\n");

    let session_start = session.started_at;

    for (i, recorded) in session.events.iter().enumerate() {
        // Timing comment: elapsed since session start, only when gap > 500ms
        if options.include_timing_comments {
            let elapsed_ms = recorded
                .timestamp
                .signed_duration_since(session_start)
                .num_milliseconds();

            let show_timing = if i == 0 {
                elapsed_ms > 500
            } else {
                let prev_ts = session.events[i - 1].timestamp;
                let gap_ms = recorded
                    .timestamp
                    .signed_duration_since(prev_ts)
                    .num_milliseconds();
                gap_ms > 500
            };

            if show_timing {
                out.push_str(&format!("\n    // +{elapsed_ms}ms\n"));
            }
        }

        match &recorded.event {
            AppEvent::DomInteraction {
                action,
                selector,
                value,
                ..
            } => {
                emit_interaction(&mut out, action, selector, value.as_deref());
            }

            AppEvent::Ipc(call) if options.include_ipc_assertions => {
                // Skip internal victauri plugin commands
                if call.command.starts_with("plugin:victauri|") {
                    continue;
                }
                if matches!(call.result, IpcResult::Ok(_)) {
                    let cmd = &call.command;
                    out.push_str(&format!(
                        "    // IPC: {cmd} completed successfully\n"
                    ));
                }
            }

            AppEvent::StateChange {
                key, caused_by, ..
            } if options.include_state_checks => {
                if caused_by.is_some() {
                    out.push_str(&format!("    // State changed: {key}\n"));
                }
            }

            // DomMutation, WindowEvent, and disabled variants are skipped
            _ => {}
        }
    }

    out.push_str("}\n");
    out
}

/// Escapes a string for embedding in a Rust string literal.
fn escape_rust_str(s: &str) -> String {
    let mut escaped = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            other => escaped.push(other),
        }
    }
    escaped
}

/// Emits a single DOM interaction as a `VictauriClient` method call.
fn emit_interaction(
    out: &mut String,
    action: &InteractionKind,
    selector: &str,
    value: Option<&str>,
) {
    let sel = escape_rust_str(selector);

    match action {
        InteractionKind::Click => {
            out.push_str(&format!(
                "    client.click(\"{sel}\").await.unwrap();\n"
            ));
        }
        InteractionKind::DoubleClick => {
            out.push_str(&format!(
                "    client.double_click(\"{sel}\").await.unwrap();\n"
            ));
        }
        InteractionKind::Fill => {
            let val = value.map_or_else(String::new, escape_rust_str);
            out.push_str(&format!(
                "    client.fill(\"{sel}\", \"{val}\").await.unwrap();\n"
            ));
        }
        InteractionKind::KeyPress => {
            let val = value.map_or_else(String::new, escape_rust_str);
            out.push_str(&format!(
                "    client.press_key(\"{val}\").await.unwrap();\n"
            ));
        }
        InteractionKind::Select => {
            let val = value.map_or_else(String::new, escape_rust_str);
            out.push_str(&format!(
                "    client.select_option(\"{sel}\", &[\"{val}\"]).await.unwrap();\n"
            ));
        }
        InteractionKind::Navigate => {
            let val = value.map_or_else(String::new, escape_rust_str);
            out.push_str(&format!(
                "    client.navigate(\"{val}\").await.unwrap();\n"
            ));
        }
        InteractionKind::Scroll => {
            out.push_str(&format!(
                "    client.scroll_to(\"{sel}\", None, None).await.unwrap();\n"
            ));
        }
    }
}

#[cfg(test)]
mod tests {
    use chrono::{Duration, Utc};

    use super::*;
    use crate::event::{AppEvent, InteractionKind, IpcCall, IpcResult};
    use crate::recording::{RecordedEvent, RecordedSession};

    fn make_session(events: Vec<RecordedEvent>) -> RecordedSession {
        RecordedSession {
            id: "test-session-001".to_string(),
            started_at: Utc::now(),
            events,
            checkpoints: vec![],
        }
    }

    fn interaction_event(
        index: usize,
        action: InteractionKind,
        selector: &str,
        value: Option<&str>,
        offset_ms: i64,
    ) -> RecordedEvent {
        RecordedEvent {
            index,
            timestamp: Utc::now() + Duration::milliseconds(offset_ms),
            event: AppEvent::DomInteraction {
                action,
                selector: selector.to_string(),
                value: value.map(String::from),
                timestamp: Utc::now() + Duration::milliseconds(offset_ms),
                webview_label: "main".to_string(),
            },
        }
    }

    #[test]
    fn empty_session_produces_valid_skeleton() {
        let session = make_session(vec![]);
        let code = generate_test_default(&session);

        assert!(code.contains("use victauri_test::VictauriClient;"));
        assert!(code.contains("#[tokio::test]"));
        assert!(code.contains("async fn recorded_flow()"));
        assert!(code.contains("VictauriClient::discover()"));
        assert!(code.contains("Session: test-session-001"));
    }

    #[test]
    fn click_generates_correct_call() {
        let session = make_session(vec![interaction_event(
            0,
            InteractionKind::Click,
            "#submit-btn",
            None,
            0,
        )]);
        let code = generate_test_default(&session);

        assert!(code.contains("client.click(\"#submit-btn\").await.unwrap();"));
    }

    #[test]
    fn fill_generates_correct_call() {
        let session = make_session(vec![interaction_event(
            0,
            InteractionKind::Fill,
            "input[name=\"email\"]",
            Some("user@example.com"),
            0,
        )]);
        let code = generate_test_default(&session);

        assert!(code.contains(
            "client.fill(\"input[name=\\\"email\\\"]\", \"user@example.com\").await.unwrap();"
        ));
    }

    #[test]
    fn ipc_comment_included_when_enabled() {
        let session = make_session(vec![RecordedEvent {
            index: 0,
            timestamp: Utc::now(),
            event: AppEvent::Ipc(IpcCall {
                id: "c1".to_string(),
                command: "save_settings".to_string(),
                timestamp: Utc::now(),
                duration_ms: Some(10),
                result: IpcResult::Ok(serde_json::json!(true)),
                arg_size_bytes: 0,
                webview_label: "main".to_string(),
            }),
        }]);
        let code = generate_test_default(&session);

        assert!(code.contains("// IPC: save_settings completed successfully"));
    }

    #[test]
    fn internal_victauri_ipc_skipped() {
        let session = make_session(vec![RecordedEvent {
            index: 0,
            timestamp: Utc::now(),
            event: AppEvent::Ipc(IpcCall {
                id: "c2".to_string(),
                command: "plugin:victauri|get_snapshot".to_string(),
                timestamp: Utc::now(),
                duration_ms: Some(2),
                result: IpcResult::Ok(serde_json::json!({})),
                arg_size_bytes: 0,
                webview_label: "main".to_string(),
            }),
        }]);
        let code = generate_test_default(&session);

        assert!(!code.contains("plugin:victauri"));
    }

    #[test]
    fn ipc_omitted_when_disabled() {
        let session = make_session(vec![RecordedEvent {
            index: 0,
            timestamp: Utc::now(),
            event: AppEvent::Ipc(IpcCall {
                id: "c1".to_string(),
                command: "save_settings".to_string(),
                timestamp: Utc::now(),
                duration_ms: Some(10),
                result: IpcResult::Ok(serde_json::json!(true)),
                arg_size_bytes: 0,
                webview_label: "main".to_string(),
            }),
        }]);
        let opts = CodegenOptions {
            include_ipc_assertions: false,
            ..CodegenOptions::default()
        };
        let code = generate_test(&session, &opts);

        assert!(!code.contains("IPC:"));
    }

    #[test]
    fn state_change_comment_included() {
        let session = make_session(vec![RecordedEvent {
            index: 0,
            timestamp: Utc::now(),
            event: AppEvent::StateChange {
                key: "user.theme".to_string(),
                timestamp: Utc::now(),
                caused_by: Some("toggle_theme".to_string()),
            },
        }]);
        let code = generate_test_default(&session);

        assert!(code.contains("// State changed: user.theme"));
    }

    #[test]
    fn custom_test_name() {
        let session = make_session(vec![]);
        let opts = CodegenOptions {
            test_name: "my_custom_test".to_string(),
            ..CodegenOptions::default()
        };
        let code = generate_test(&session, &opts);

        assert!(code.contains("async fn my_custom_test()"));
    }

    #[test]
    fn special_chars_escaped() {
        let session = make_session(vec![interaction_event(
            0,
            InteractionKind::Fill,
            "input",
            Some("line1\nline2\ttab\"quote\\back"),
            0,
        )]);
        let code = generate_test_default(&session);

        assert!(code.contains("\\n"));
        assert!(code.contains("\\t"));
        assert!(code.contains("\\\""));
        assert!(code.contains("\\\\"));
    }

    #[test]
    fn all_interaction_kinds_generate_code() {
        let session = make_session(vec![
            interaction_event(0, InteractionKind::Click, "#a", None, 0),
            interaction_event(1, InteractionKind::DoubleClick, "#b", None, 10),
            interaction_event(2, InteractionKind::Fill, "#c", Some("val"), 20),
            interaction_event(3, InteractionKind::KeyPress, "#d", Some("Enter"), 30),
            interaction_event(4, InteractionKind::Select, "#e", Some("opt1"), 40),
            interaction_event(5, InteractionKind::Navigate, "#f", Some("/page"), 50),
            interaction_event(6, InteractionKind::Scroll, "#g", None, 60),
        ]);
        let code = generate_test(&session, &CodegenOptions {
            include_timing_comments: false,
            ..CodegenOptions::default()
        });

        assert!(code.contains("client.click(\"#a\")"));
        assert!(code.contains("client.double_click(\"#b\")"));
        assert!(code.contains("client.fill(\"#c\", \"val\")"));
        assert!(code.contains("client.press_key(\"Enter\")"));
        assert!(code.contains("client.select_option(\"#e\", &[\"opt1\"])"));
        assert!(code.contains("client.navigate(\"/page\")"));
        assert!(code.contains("client.scroll_to(\"#g\", None, None)"));
    }

    #[test]
    fn dom_mutation_and_window_event_skipped() {
        let ts = Utc::now();
        let session = make_session(vec![
            RecordedEvent {
                index: 0,
                timestamp: ts,
                event: AppEvent::DomMutation {
                    webview_label: "main".to_string(),
                    timestamp: ts,
                    mutation_count: 5,
                },
            },
            RecordedEvent {
                index: 1,
                timestamp: ts,
                event: AppEvent::WindowEvent {
                    label: "main".to_string(),
                    event: "focus".to_string(),
                    timestamp: ts,
                },
            },
        ]);
        let code = generate_test_default(&session);

        // Should only have the skeleton, no interaction or assertion lines
        assert!(!code.contains("client."));
        assert!(!code.contains("// IPC:"));
        assert!(!code.contains("// State"));
    }

    #[test]
    fn default_options_are_correct() {
        let opts = CodegenOptions::default();
        assert_eq!(opts.test_name, "recorded_flow");
        assert!(opts.include_ipc_assertions);
        assert!(opts.include_state_checks);
        assert!(opts.include_timing_comments);
    }
}
